# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[9.49759869e-01, 8.74484975e-01, 2.26322177e-01],
       [5.07608531e-01, 8.58059486e-01, 9.47825856e-01],
       [4.89858674e-01, 3.34987768e-01, 8.79065745e-01],
       [1.78185735e-01, 6.91454157e-01, 4.93286199e-01],
       [8.10247823e-01, 5.43188836e-01, 4.70698841e-01],
       [7.77129970e-01, 5.19777327e-01, 1.49186759e-02],
       [4.70833658e-01, 6.58168514e-01, 7.69230678e-01],
       [3.10764218e-01, 8.79452774e-01, 9.08764806e-01],
       [2.14812719e-01, 4.40556409e-01, 3.82250008e-01],
       [1.76289478e-01, 7.42610301e-01, 5.46515218e-01],
       [6.05500256e-01, 3.26414519e-01, 2.02944374e-01],
       [3.72093632e-01, 1.12328962e-01, 2.14945708e-01],
       [8.63306263e-01, 9.07669958e-01, 5.59322920e-02],
       [2.56102385e-01, 6.52814391e-01, 7.90822908e-01],
       [1.96574856e-02, 3.35598207e-01, 6.60720951e-01],
       [7.05482212e-01, 1.60764974e-01, 5.91965931e-01],
       [6.26505906e-01, 7.72428940e-01, 9.29431313e-01],
       [5.37531622e-01, 7.60961

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.17818573, 0.69145416, 0.4932862 ],
       [0.92975956, 0.07161793, 0.52080476]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
clusters = vq(data, clust_centers)
clusters

(array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 0, 1, 1, 1, 0, 0]),
 array([0.83671782, 0.58556213, 0.61076523, 0.        , 0.48905294,
        0.69286605, 0.40360389, 0.47491368, 0.27680363, 0.07385036,
        0.52067323, 0.63733698, 0.84108136, 0.3099873 , 0.42402719,
        0.25161764, 0.63069046, 0.48588196, 0.75615371, 0.41197541,
        0.49052948, 0.57301818, 0.        , 0.5675432 , 0.65365657,
        0.4043505 , 0.71481329, 0.29518981, 0.39653812, 0.78997505]))

In [6]:
labels = clusters[0]
labels

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0])

In [7]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

In [ ]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


In [8]:
from scipy.cluster.vq import kmeans

In [9]:
kmeans(data, clust_centers)

(array([[0.40979719, 0.6265861 , 0.75798251],
        [0.71750237, 0.41500496, 0.28866756]]), 0.3963959879710594)

In [10]:
kmeans(data, 2)

(array([[0.71750237, 0.41500496, 0.28866756],
        [0.40979719, 0.6265861 , 0.75798251]]), 0.3963959879710594)